package:
  name: argo-cd
  version: 2.7.0
  epoch: 0
  description: Declarative continuous deployment for Kubernetes.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - go
      - python3
      - nodejs-16
      - yarn

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/argoproj/argo-cd
      tag: v${{package.version}}
      expected-commit: c592219140e5f48b6849f3f9a8f7aed6047d54fa

  - runs: |
      cp ui/package.json .
      cp ui/yarn.lock .
      yarn install
      yarn cache clean

      # Our global LDFLAGS conflict with a Makefile parameter
      unset LDFLAGS
      make argocd-all

      mkdir -p ${{targets.destdir}}/usr/bin
      mv dist/argocd* ${{targets.destdir}}/usr/bin/

      ln -s /usr/bin/argocd ${{targets.destdir}}/usr/bin/argocd-server
      ln -s /usr/bin/argocd ${{targets.destdir}}/usr/bin/argocd-repo-server
      ln -s /usr/bin/argocd ${{targets.destdir}}/usr/bin/argocd-cmp-server
      ln -s /usr/bin/argocd ${{targets.destdir}}/usr/bin/argocd-application-controller
      ln -s /usr/bin/argocd ${{targets.destdir}}/usr/bin/argocd-dex
      ln -s /usr/bin/argocd ${{targets.destdir}}/usr/bin/argocd-notifications
      ln -s /usr/bin/argocd ${{targets.destdir}}/usr/bin/argocd-applicationset-controller
      ln -s /usr/bin/argocd ${{targets.destdir}}/usr/bin/argocd-k8s-auth

  - uses: strip

update:
  enabled: true
  github:
    identifier: argoproj/argo-cd
    strip-prefix: v
