package:
  name: gitea
  version: 1.22.1
  epoch: 5
  description: self-hosted git service
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 35c5192b2572041f14a4d33cbd0128da887b360e
      repository: https://github.com/go-gitea/gitea
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: .
      ldflags: -X "main.Version=v${{package.version}}"
      output: gitea

update:
  enabled: true
  github:
    identifier: go-gitea/gitea
    strip-prefix: v
