package:
  name: gitea
  version: 1.22.1
  epoch: 0
  description: self-hosted git service
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
      - nodejs
      - npm

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 35c5192b2572041f14a4d33cbd0128da887b360e
      repository: https://github.com/go-gitea/gitea
      tag: v${{package.version}}

  - runs: |
      set -x
      npm install --no-save
      BROWSERSLIST_IGNORE_OLD_DATA=true npx webpack

  - runs: |
      set -x
      CC= GOOS= GOARCH= CGO_ENABLED=0 go generate -tags 'bindata timetzdata sqlite sqlite_unlock_notify' ./...

  - uses: go/build
    with:
      packages: .
      ldflags: -X "main.Version=v${{package.version}}"
      output: gitea
      tags: netgo,osusergo,bindata,timetzdata,sqlite,sqlite_unlock_notify

test:
  pipeline:
    - name: Verify Gitea
      runs: |
        # Check if binary runs
        /usr/bin/gitea --help

update:
  enabled: true
  github:
    identifier: go-gitea/gitea
    strip-prefix: v
