package:
  name: kafka
  # When bumping check to see if the CVE mitigation can be removed.
  version: "3.4.0"
  epoch: 2
  description:
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation:
      license: Apache-2.0
  dependencies:
    runtime:
      - bash # some helper scripts use bash
      - openjdk-11-jre

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - curl
      - gradle
      - sbt
      - openjdk-11

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/apache/kafka
      tag: ${{package.version}}
      expected-commit: 2e1947d240607d53f071f61c875cfffc3fec47fe

  - runs: |
      export LANG=en_US.UTF-8

      # Mitigate CVE-2023-26048 and CVE-2023-26049 by bumping jetty
      sed -i 's/\(jetty:\s*"\)[^"]\+"/\19.4.51.v20230217"/' gradle/dependencies.gradle

      ./gradlew clean releaseTarGz

      tar -xf core/build/distributions/kafka_2.13-${{package.version}}.tgz

      mkdir -p ${{targets.destdir}}/usr/lib/kafka

      mv kafka_2.13-${{package.version}}/bin ${{targets.destdir}}/usr/lib/kafka
      mv kafka_2.13-${{package.version}}/libs ${{targets.destdir}}/usr/lib/kafka
      mv kafka_2.13-${{package.version}}/config ${{targets.destdir}}/usr/lib/kafka

      # Clean up windows
      rm -rf ${{targets.destdir}}/usr/lib/kafka/bin/*.bat

update:
  enabled: true
  github:
    identifier: apache/kafka
    use-tag: true

advisories:
  CVE-2023-26048:
    - timestamp: 2023-05-02T08:42:50.301866-04:00
      status: fixed
      fixed-version: 3.4.0-r2
  CVE-2023-26049:
    - timestamp: 2023-05-02T08:43:01.711354-04:00
      status: fixed
      fixed-version: 3.4.0-r2

secfixes:
  3.4.0-r2:
    - CVE-2023-26048
    - CVE-2023-26049
