package:
  name: kubescape
  version: 2.3.0
  epoch: 0
  description: "Kubescape is an open-source Kubernetes security platform for your IDE, CI/CD pipelines, and clusters. It includes risk analysis, security, compliance, and misconfiguration scanning, saving Kubernetes users and administrators precious time, effort, and resources."
  copyright:
    - license: Apache-2.0 AND MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - go
      - git
      - cmake

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubescape/kubescape
      tag: v${{package.version}}
      expected-commit: b93a97a8c839d65137b8b572ad86f6bb56ee4921
      destination: kubescape

  - runs: |
      cd kubescape
      export CGO_ENABLED=1
      make libgit2
      python3 --version && python3 build.py
      install -Dm755  ./build/kubescape-ubuntu-latest ${{targets.destdir}}/usr/bin/kubescape

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubescape/kubescape
    strip-prefix: v
