package:
  name: pulumi-language-java
  version: 0.9.2
  epoch: 0
  description: Pulumi Language SDK for Java
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - go
      - busybox
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pulumi/pulumi-java.git
      tag: v${{package.version}}
      destination: ${{package.name}}
      expected-commit: 9ed55571c504dc26c0a9226f359c5aa0b1d15fdb

  - working-directory: ${{package.name}}
    pipeline:
      - runs: |
          set -x
          export CGO_ENABLED=0 GO111MODULE=on
          cd pkg/
          go build \
            -o "${{targets.destdir}}/usr/bin/pulumi-language-java" \
            -ldflags="-X github.com/pulumi/pulumi-java/pkg/version.Version=v${{package.version}}" \
            ./cmd/pulumi-language-java
      - uses: strip

update:
  enabled: true
  github:
    identifier: pulumi/pulumi-java
    strip-prefix: v
