package:
  name: pulumi-kubernetes-operator
  version: 1.11.5
  epoch: 0
  description: A Kubernetes Operator that automates the deployment of Pulumi Stacks
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - go
      - busybox
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pulumi/pulumi-kubernetes-operator.git
      tag: v${{package.version}}
      destination: ${{package.name}}
      expected-commit: e3f9416a288067828cba13813989aa8a6d5cb9eb

  - working-directory: ${{package.name}}
    pipeline:
      - runs: |
          # Original Go build args found in ./scripts/build.sh
          CGO_ENABLED=0 go build -o "${{targets.destdir}}/usr/bin/${{package.name}}" \
            -ldflags "-X github.com/pulumi/pulumi-kubernetes-operator/version.Version=v${{package.version}} -w -extldflags \"-static\"" \
            -tags netgo ./cmd/manager/main.go
      - uses: strip

update:
  enabled: true
  github:
    identifier: pulumi/pulumi-kubernetes-operator
    strip-prefix: v
