package:
  name: pulumi-language-dotnet
  version: 3.54.1
  epoch: 0
  description: Pulumi Language SDK for Dotnet
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - go
      - busybox
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pulumi/pulumi-dotnet.git
      tag: v${{package.version}}
      destination: ${{package.name}}
      expected-commit: da9240106c8f740175922f188462fed6446042b7

  - working-directory: ${{package.name}}
    pipeline:
      - runs: |
          set -x
          export CGO_ENABLED=0 GO111MODULE=on
          cd pulumi-language-dotnet/
          go build \
            -o "${{targets.destdir}}/usr/bin/pulumi-language-dotnet" \
            -ldflags="-X github.com/pulumi/pulumi-dotnet/pulumi-language-dotnet/version.Version=v${{package.version}}" \
            .

update:
  enabled: true
  github:
    identifier: pulumi/pulumi-dotnet
    strip-prefix: v
