package:
  name: py3-urllib3
  version: 2.0.1
  epoch: 0
  description: "HTTP library with thread-safe connection pooling, file post, and more"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - py3-pip

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/urllib3/urllib3.git
      tag: ${{package.version}}
      expected-commit: b85e93d619a323b92c2954da852857e0119d71b8

  - runs: |
      # This is needed to work around the error "ValueError: ZIP does not support timestamps before 1980"
      export SOURCE_DATE_EPOCH=315532800
      pip install . --prefix=/usr --root=${{targets.destdir}}

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - (\d+\.\d+)\.\da\d+ # urllib3 releases alpha versions with a suffix "a" followed by a digit, let's ignore these
  github:
    identifier: urllib3/urllib3
