name: Wolfictl Lint

on:
  pull_request:
    branches: ['main']
  push:
    branches:
      - gh-readonly-queue/main/**

jobs:
  lint:
    name: Wolfictl Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Lint
      id: lint
      uses: docker://ghcr.io/wolfi-dev/wolfictl:latest@sha256:4d76b62ed629cb49f2147fd1136bac668a51c63e62ad9bc4d03e12f2a54c8f62
      with:
        entrypoint: wolfictl
        args: lint
    - name: Enforce YAML formatting
      id: lint-yaml
      uses: docker://ghcr.io/wolfi-dev/wolfictl:latest@sha256:4d76b62ed629cb49f2147fd1136bac668a51c63e62ad9bc4d03e12f2a54c8f62
      with:
        entrypoint: wolfictl
        args: lint yam
    - name: Advisory sync
      id: advisory
      uses: docker://ghcr.io/wolfi-dev/wolfictl:latest@sha256:4d76b62ed629cb49f2147fd1136bac668a51c63e62ad9bc4d03e12f2a54c8f62
      with:
        entrypoint: wolfictl
        args: "advisory sync-secfixes --warn"
