name: Wolfictl Update From GitHub

on:
  workflow_dispatch:
  # Triggers the workflow every hour
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: write
  pull-requests: write

env:
  GIT_AUTHOR_NAME: wolfi-bot
  GIT_AUTHOR_EMAIL: 121097084+wolfi-bot@users.noreply.github.com

jobs:
  update:
    name: Wolfictl Update
    if: github.repository == 'wolfi-dev/os'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: docker://ghcr.io/wolfi-dev/wolfictl:latest@sha256:4d76b62ed629cb49f2147fd1136bac668a51c63e62ad9bc4d03e12f2a54c8f62
      with:
        entrypoint: wolfictl
        args: update https://github.com/${{github.repository}} --release-monitoring-query=false
      env:
        GITHUB_TOKEN: ${{ secrets.WOLFI_BOT_CLASSIC_PAT }}
        GIT_AUTHOR_NAME: ${{ env.GIT_AUTHOR_NAME }}
        GIT_AUTHOR_EMAIL: ${{ env.GIT_AUTHOR_EMAIL }}
